### ISSUE TITLE
unknown command line option: -z

### ISSUE THREAD

**Issue by try-agaaain** [ksco/rvld#4]
我在codespace上进行的实验，按照文档中的方式执行下面的命令搭建了开发环境：
```shell
apt update
apt install -y gcc-10-riscv64-linux-gnu qemu-user
ln -sf /usr/bin/riscv64-linux-gnu-gcc-10 /usr/bin/riscv64-linux-gnu-gcc
```
但是执行`make test` 后出现了下面的错误：
```console
@try-agaaain ➜ /workspaces/rvld (1a06a3d) $ make test
make[1]: Entering directory '/workspaces/rvld'
Testing tests/hello.sh
rvld: fatal: unknown command line option: -z
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/ksco/rvld/pkg/utils.Fatal({0x4a44a0?, 0xc00008c670?})
        /workspaces/rvld/pkg/utils/utils.go:13 +0x65
main.parseArgs(0xc000088f40)
        /workspaces/rvld/rvld.go:123 +0xee8
main.main()
        /workspaces/rvld/rvld.go:15 +0x5d
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:16: tests/hello.sh] Error 1
make[1]: Leaving directory '/workspaces/rvld'
make: *** [Makefile:10: test] Error 2
```

之后我通过`fmt.Printf("info: %s\n", os.Args)`打印了所执行的命令，输出如下：
```console
info: [./ld -plugin /usr/lib/gcc-cross/riscv64-linux-gnu/10/liblto_plugin.so -plugin-opt=/usr/lib/gcc-cross/
riscv64-linux-gnu/10/lto-wrapper -plugin-opt=-fresolution=/tmp/cc6Z1UGm.res -plugin-opt=-pass-through
=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --sysroot=/ --build-id -hash-style
=gnu --as-needed -melf64lriscv -static -z relro -o out/tests/hello/out /usr/lib/gcc-cross/riscv64-linux-gnu/10
/../../../../riscv64-linux-gnu/lib/crt1.o /usr/lib/gcc-cross/riscv64-linux-gnu/10/crti.o /usr/lib/gcc-cross/riscv64
-linux-gnu/10/crtbeginT.o -L. -L/usr/lib/gcc-cross/riscv64-linux-gnu/10 -L/usr/lib/gcc-cross/riscv64-linux-gnu
/10/../../../../riscv64-linux-gnu/lib -L/lib/riscv64-linux-gnu -L/usr/lib/riscv64-linux-gnu out/tests/hello/a.o
 --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc-cross/riscv64-linux-gnu/10/crtend.o /usr/lib/
gcc-cross/riscv64-linux-gnu/10/crtn.o]
```

不是很清楚出现这个问题的原因。

我的环境信息如下：
```console
@try-agaaain ➜ /workspaces/rvld (1a06a3d) $ go version
go version go1.20.7 linux/amd64
@try-agaaain ➜ /workspaces/rvld (1a06a3d) $ uname -a
Linux codespaces-e262ed 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by ksco** [comment]
可能是工具链的版本原因，直接修改代码忽略掉这个参数即可。
